import CGravity
import Foundation

/// Owns native memory and keeps module code alive. A recursive lock serializes
/// every C invocation and host callback. Instances retain their module, and the
/// module retains no Swift instance handles, avoiding an ownership cycle.
public final class NativeModule: @unchecked Sendable {
    public let declarations: [NativeDeclaration]
    public let types: [NativeType]
    private let lock = NSRecursiveLock()
    private let module: UnsafePointer<gravity_aot_module>
    private let codeOwner: AnyObject?
    private let typePointers: [String: UnsafePointer<gravity_aot_class>]
    private let allocationLimit: Int
    private let fuelPerCall: UInt64
    private let context: UnsafeMutablePointer<gravity_aot_context>
    private var bridge = gravity_aot_host()
    private var allocations: [UnsafeMutableRawPointer] = []
    private var allocatedBytes = 0
    private var handles: [UnsafeMutableRawPointer: any NativeHostObject] = [:]
    private var active = false
    private var hostError: String?

    /// `module` must point to valid trusted metadata generated by Gravity.
    /// Retain a dynamic-library owner here when the module is not statically linked.
    public init(
        module: UnsafePointer<gravity_aot_module>, retaining owner: AnyObject? = nil,
        allocationLimit: Int = 64 * 1024 * 1024, fuelPerCall: UInt64 = 1_000_000
    ) throws {
        guard module.pointee.abi_version == GRAVITY_AOT_ABI_VERSION else {
            throw NativeRuntimeError.incompatibleABI(module.pointee.abi_version)
        }
        guard allocationLimit > 0, fuelPerCall > 0 else { throw NativeRuntimeError.allocationLimit }
        self.module = module; self.codeOwner = owner; self.allocationLimit = allocationLimit; self.fuelPerCall = fuelPerCall
        declarations = try nativeArray(module.pointee.declarations, module.pointee.declaration_count).map {
            // The buffer points at immutable metadata for the module lifetime.
            var copy = $0
            return try withUnsafePointer(to: &copy, nativeDeclaration)
        }
        let rawTypes = try nativeArray(module.pointee.types, module.pointee.type_count)
        var pointers: [String: UnsafePointer<gravity_aot_class>] = [:]
        var values: [NativeType] = []
        for (index, type) in rawTypes.enumerated() {
            guard let declaration = type.declaration, let base = rawTypes.baseAddress else {
                throw NativeRuntimeError.malformedMetadata("Missing type declaration")
            }
            let d = try nativeDeclaration(declaration)
            guard pointers[d.name] == nil else { throw NativeRuntimeError.malformedMetadata("Duplicate type \(d.name)") }
            pointers[d.name] = base.advanced(by: index)
            let fields = try nativeArray(type.fields, type.field_count).map { field in
                guard let declaration = field.declaration else { throw NativeRuntimeError.malformedMetadata("Missing field declaration") }
                return NativeType.Field(declaration: try nativeDeclaration(declaration), defaultValue: try nativeLiteral(field.default_value), isReadOnly: field.readonly != 0)
            }
            let methods = try nativeArray(type.methods, type.method_count).map { method in
                guard let declaration = method.declaration, method.call != nil else {
                    throw NativeRuntimeError.malformedMetadata("Missing method declaration or callback")
                }
                return try nativeDeclaration(declaration)
            }
            values.append(NativeType(declaration: d, fields: fields, methods: methods))
        }
        types = values; typePointers = pointers
        // C invokes Swift callbacks while this context is live. Store it in owned
        // C memory, rather than taking an inout access to a Swift stored property.
        context = .allocate(capacity: 1)
        context.initialize(to: gravity_aot_context_init(0))
        bridge = gravity_aot_host(get: Self.bridgeGet, set: Self.bridgeSet, call: Self.bridgeCall, next: Self.bridgeNext)
    }

    deinit {
        context.deinitialize(count: 1); context.deallocate()
        for pointer in allocations { pointer.deallocate() }
    }

    public func makeInstance(type name: String, arguments: [NativeValue] = []) throws -> NativeInstance {
        try lock.withLock {
            guard let type = typePointers[name] else { throw NativeRuntimeError.unknownType(name) }
            return try scope {
                let args = try arguments.map(encode)
                let raw = args.withUnsafeBufferPointer { gravity_aot_construct(context, type, $0.baseAddress, UInt32($0.count)) }
                try check()
                return NativeInstance(owner: self, raw: raw, typeName: name)
            }
        }
    }

    @discardableResult
    public func invoke(
        _ instance: NativeInstance, method: String, arguments: [NativeValue] = [], bindings: [String: NativeValue] = [:]
    ) throws -> NativeValue {
        try lock.withLock {
            try validate(instance)
            return try scope {
                for (name, value) in bindings {
                    let raw = try encode(value)
                    _ = name.withCString { gravity_aot_set(context, instance.raw, $0, raw) }
                    try check()
                }
                let args = try arguments.map(encode)
                let value = method.withCString { name in
                    args.withUnsafeBufferPointer { gravity_aot_call(context, instance.raw, name, $0.baseAddress, UInt32($0.count)) }
                }
                try check()
                return try decode(value)
            }
        }
    }

    public func read(_ instance: NativeInstance, field: String) throws -> NativeValue {
        try lock.withLock {
            try validate(instance)
            return try scope {
                let value = field.withCString { gravity_aot_get(context, instance.raw, $0) }
                try check(); return try decode(value)
            }
        }
    }

    public func write(_ instance: NativeInstance, field: String, value: NativeValue) throws {
        try lock.withLock {
            try validate(instance)
            try scope {
                let raw = try encode(value)
                _ = field.withCString { gravity_aot_set(context, instance.raw, $0, raw) }; try check()
            }
        }
    }

    private func validate(_ instance: NativeInstance) throws {
        guard instance.owner === self else { throw NativeRuntimeError.foreignInstance }
    }
    private func scope<T>(_ body: () throws -> T) throws -> T {
        guard !active else { throw NativeRuntimeError.reentrantCall }
        active = true; context.pointee.error = 0; context.pointee.fuel = fuelPerCall; context.pointee.depth = 0
        context.pointee.host_generation &+= 1; hostError = nil
        context.pointee.allocate = Self.allocate
        context.pointee.allocation_data = Unmanaged.passUnretained(self).toOpaque()
        context.pointee.host_data = Unmanaged.passUnretained(self).toOpaque()
        defer {
            context.pointee.host = nil; handles.removeAll(keepingCapacity: true); active = false
        }
        return try withUnsafePointer(to: &bridge) { pointer in
            context.pointee.host = pointer
            return try body()
        }
    }
    private func check() throws {
        guard context.pointee.error == 0 else { throw NativeRuntimeError.runtime(code: context.pointee.error, detail: hostError) }
    }
    private func encode(_ value: NativeValue) throws -> gravity_aot_value {
        switch value {
        case .null: return gravity_aot_null()
        case let .boolean(v): return gravity_aot_bool(v ? 1 : 0)
        case let .integer(v): return gravity_aot_int(v)
        case let .double(v): return gravity_aot_float(v)
        case let .string(v):
            let bytes = Array(v.utf8)
            guard bytes.count < Int(UInt32.max), let p = allocateBytes(bytes.count + 1) else { throw NativeRuntimeError.allocationLimit }
            let chars = p.assumingMemoryBound(to: UInt8.self)
            for (i, byte) in bytes.enumerated() { chars[i] = byte }; chars[bytes.count] = 0
            return gravity_aot_string(UnsafeRawPointer(p).assumingMemoryBound(to: CChar.self), UInt32(bytes.count))
        case let .object(v): try validate(v); return v.raw
        case let .host(v):
            let pointer = Unmanaged.passUnretained(v as AnyObject).toOpaque()
            handles[pointer] = v
            return gravity_aot_host_ref(context, pointer)
        case let .list(v):
            guard v.count < Int(UInt32.max) else { throw NativeRuntimeError.unsupportedValue }
            let raw = try v.map(encode)
            let list = raw.withUnsafeBufferPointer { gravity_aot_list_new(context, $0.baseAddress, UInt32($0.count)) }
            try check(); return list
        }
    }
    private func decode(_ raw: gravity_aot_value, depth: Int = 0) throws -> NativeValue {
        guard depth < 64 else { throw NativeRuntimeError.unsupportedValue }
        switch raw.kind {
        case 0...4: return try NativeValue(nativeLiteral(raw))
        case 5:
            guard let object = raw.object, let declaration = object.pointee.type?.pointee.declaration else {
                throw NativeRuntimeError.unsupportedValue
            }
            let name = try nativeString(declaration.pointee.name)
            guard typePointers[name] == object.pointee.type else { throw NativeRuntimeError.foreignInstance }
            return .object(NativeInstance(owner: self, raw: raw, typeName: name))
        case 6:
            guard raw.length == context.pointee.host_generation, let p = raw.handle, let host = handles[p] else {
                throw NativeRuntimeError.runtime(code: UInt32(GRAVITY_AOT_STALE_HANDLE), detail: nil)
            }
            return .host(host)
        case 7:
            guard let list = raw.list else { throw NativeRuntimeError.unsupportedValue }
            return .list(try nativeArray(UnsafePointer(list.pointee.items), list.pointee.count).map { try decode($0, depth: depth + 1) })
        default: throw NativeRuntimeError.unsupportedValue
        }
    }
    private func allocateBytes(_ count: Int) -> UnsafeMutableRawPointer? {
        guard count > 0, count <= allocationLimit - allocatedBytes else {
            hostError = "Native module allocation limit exceeded"; return nil
        }
        let pointer = UnsafeMutableRawPointer.allocate(byteCount: count, alignment: 16)
        allocations.append(pointer); allocatedBytes += count; return pointer
    }
    private static func owner(_ data: UnsafeMutableRawPointer?) -> NativeModule? {
        data.map { Unmanaged<NativeModule>.fromOpaque($0).takeUnretainedValue() }
    }
    private static let allocate: @convention(c) (UnsafeMutableRawPointer?, Int) -> UnsafeMutableRawPointer? = { data, size in
        owner(data)?.allocateBytes(size)
    }
    private func performBridge(_ body: () throws -> Int32) -> Int32 {
        do { return try body() } catch { if hostError == nil { hostError = String(describing: error) }; return 0 }
    }
    private func host(_ value: gravity_aot_value) throws -> any NativeHostObject {
        guard case let .host(host) = try decode(value) else { throw NativeRuntimeError.unsupportedValue }
        return host
    }
    private static let bridgeGet: @convention(c) (UnsafeMutableRawPointer?, gravity_aot_value, UnsafePointer<CChar>?, UnsafeMutablePointer<gravity_aot_value>?) -> Int32 = { data, target, key, out in
        guard let owner = owner(data), let key, let out else { return 0 }
        return owner.performBridge {
            guard let value = try owner.host(target).read(String(cString: key)) else { return 0 }
            out.pointee = try owner.encode(value); return 1
        }
    }
    private static let bridgeSet: @convention(c) (UnsafeMutableRawPointer?, gravity_aot_value, UnsafePointer<CChar>?, gravity_aot_value) -> Int32 = { data, target, key, value in
        guard let owner = owner(data), let key else { return 0 }
        return owner.performBridge { try owner.host(target).write(String(cString: key), value: owner.decode(value)) ? 1 : 0 }
    }
    private static let bridgeCall: @convention(c) (UnsafeMutableRawPointer?, gravity_aot_value, UnsafePointer<CChar>?, UnsafePointer<gravity_aot_value>?, UInt32, UnsafeMutablePointer<gravity_aot_value>?) -> Int32 = { data, target, name, args, count, out in
        guard let owner = owner(data), let name, let out else { return 0 }
        return owner.performBridge {
            let values = try nativeArray(args, count).map { try owner.decode($0) }
            guard let value = try owner.host(target).call(String(cString: name), arguments: values) else { return 0 }
            out.pointee = try owner.encode(value); return 1
        }
    }
    private static let bridgeNext: @convention(c) (UnsafeMutableRawPointer?, gravity_aot_value, UnsafeMutablePointer<UInt64>?, UnsafeMutablePointer<gravity_aot_value>?) -> Int32 = { data, target, state, out in
        guard let owner = owner(data), let state, let out else { return -1 }
        var failed = false
        let result = owner.performBridge {
            do {
                guard let value = try owner.host(target).next(state: &state.pointee) else { return 0 }
                out.pointee = try owner.encode(value); return 1
            } catch { failed = true; throw error }
        }
        return failed ? -1 : result
    }
}
